version: '2'
services:

    # Web server container
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./web/docs/:/var/www/docs/
        links:
            - python
        ports:
            - "80:80"
            - "8000:8000"
        depends_on:
            - python
        restart: unless-stopped

    # Application container
    python:
        build:
            context: ./
            dockerfile: ./docker/python/Dockerfile
        environment:
            - DEBUG=true
            - PORT=8080
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB_NAME=acme
            - MONGO_TEST_DB_NAME=acme_test
        volumes:
            - ./:/server/http
        links:
            - mongodb
        depends_on:
            - mongodb
        restart: unless-stopped

    # Database container
    mongodb:
        image: mvertes/alpine-mongo:3.2.3
        restart: unless-stopped
